<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/Class_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing necessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [ ]:
# load the dataset
data = pd.read_csv("hiring.csv")
data

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
# check the shape
data.shape

(8, 4)

In [ ]:
# check summary stats
data.describe()

       test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [ ]:
# checking info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  8 non-null      object
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [ ]:
# checking missing values
data.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [ ]:
# filling in missing values using fillna
data.fillna({'experience' : data['experience'].mode()[0]}, inplace=True)
data.fillna({'test_score(out of 10)' : data['test_score(out of 10)'].median()}, inplace=True)

In [ ]:
# check null values again
data.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [ ]:
# changing column name
data.rename(columns={'test_score(out of 10)' : 'test_score', 'interview_score(out of 10)' : 'interview_score', 'salary($)': 'salary'}, inplace=True)

In [ ]:
data.head()

  experience  test_score  interview_score  salary
0     eleven         8.0                9   50000
1     eleven         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [ ]:
# preprocessing using get dummies -- converting experience to numerical values
dummy = pd.get_dummies(data[['experience']], drop_first=True, dtype=int)
dummy

,experience_five,experience_seven,experience_ten,experience_three,experience_two
0,0,0,0,0,0
1,0,0,0,0,0
2,1,0,0,0,0
3,0,0,0,0,1
4,0,1,0,0,0
5,0,0,0,1,0
6,0,0,1,0,0
7,0,0,0,0,0

In [ ]:
# merging
df_merged = pd.concat([data, dummy], axis = 1)
df_merged

,test_score,interview_score,salary,experience_five,experience_seven,experience_ten,experience_three,experience_two
0,8.0,9,50000,0,0,0,0,0
1,8.0,6,45000,0,0,0,0,0
2,6.0,7,60000,1,0,0,0,0
3,10.0,10,65000,0,0,0,0,1
4,9.0,6,70000,0,1,0,0,0
5,7.0,10,62000,0,0,0,1,0
6,8.0,7,72000,0,0,1,0,0
7,7.0,8,80000,0,0,0,0,0

In [ ]:
# removing experience column
# df_merged.drop('experience',axis = 1,inplace=True)
#df_merged -- this has already been dropped