<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/cohort2_Python_Data_Cleaning_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Data Cleaning: Basics Revision

## 1.0 Importing our Libraries

In [ ]:
# Importing the Pandas Library
#
import pandas as pd

# Importing the Numpy Library
#
import numpy as np

## 1.1 Validity

In [ ]:
# Example 1: Irrelevant Data
# Irrelevant data are those that are not actually needed, and don’t fit under
# the context of the problem we’re trying to solve.
# For example, we will drop the Team and Weight columns from the dataset below
# since we will not need them in our analysis
#

# Making the dataframe from csv file
data_df = pd.read_csv("http://bit.ly/MSDS-NBADataset", index_col ="Name" )
data_df

# Dropping the irrelevant columns i.e. Team and Weight
# Those values were dropped since axis was set equal to 1 and
# the changes were made in the original data frame since inplace was True.
data_df.drop(["Team", "Weight"], axis = 1, inplace = True)

# Display the resulting dataframe
data_df

               Number Position   Age Height            College     Salary
Name
Avery Bradley     0.0       PG  25.0    6-2              Texas  7730337.0
Jae Crowder      99.0       SF  25.0    6-6          Marquette  6796117.0
John Holland     30.0       SG  27.0    6-5  Boston University        NaN
R.J. Hunter      28.0       SG  22.0    6-5      Georgia State  1148640.0
Jonas Jerebko     8.0       PF  29.0   6-10                NaN  5000000.0
...               ...      ...   ...    ...                ...        ...
Shelvin Mack      8.0       PG  26.0    6-3             Butler  2433333.0
Raul Neto        25.0       PG  24.0    6-1                NaN   900000.0
Tibor Pleiss     21.0        C  26.0    7-3                NaN  2900000.0
Jeff Withey      24.0        C  26.0    7-0             Kansas   947276.0
NaN               NaN      NaN   NaN    NaN                NaN        NaN

[458 rows x 6 columns]

In [ ]:
# Example 2: Syntax Errors
# We can also remove any syntax error that we find in our records.
# Remove white spaces: Extra white spaces at the beginning or the end of a string should be removed.
# Pad strings: Strings can be padded with spaces or other characters to a certain width i.e. 313 => 000313 (6 digits).
# Let's remove use the str.strip function on the respective column name to strip the leading and trailing space
#

# Creating the DataFrame to be used
df1 = {
    'County':['     Nairobi     ', ' Machakos       ', ' Kisumu', 'Nakuru       ', 'Naroko '],
   'Score':[73, 83, 75, 84, 61]}

df1 = pd.DataFrame(df1,columns=['County','Score'])

# Displaying the resulting dataframe
df1['County']

0         Nairobi
1      Machakos
2               Kisumu
3        Nakuru
4              Naroko
Name: County, dtype: object

In [ ]:
# Example 2: Syntax Errors
# We can use the str.strip function on the respective column name to strip the leading and trailing spaces
#

df1['County'] = df1['County'].str.strip()


# Displaying the resulting dataframe
df1['County']

In [ ]:
# Example 3: Syntax Errors
# We can also use str.replace() function on the respective column to strip all the spaces (white space)
#

df1['County'] = df1['County'].str.replace(" ","")

# Displaying the resulting dataframe
df1

     County  Score
0   Nairobi     73
1  Machakos     83
2    Kisumu     75
3    Nakuru     84
4    Naroko     61

In [ ]:
# Example 4:
# Fix typos: Strings can be entered in many different ways, and no wonder they can have mistakes.
#

# If you want to replace certain words - "Naroko" with "Narok"
df1['County'] = df1['County'].str.replace('Naroko', 'Narok')

df1

     County  Score
0   Nairobi     73
1  Machakos     83
2    Kisumu     75
3    Nakuru     84
4     Narok     61

In this section, we also handle outliers in our datasets. Examples of challenges of identify and handling outliers can be found in a different session.

### <font color="green">1.1 Challenges</font>

In [ ]:
#dropping irrelevany colunm
df4(["Country Code"], axis = 1, inplace = True)

In [ ]:
# Challenge 2
# Use the lstrip() function of .str method to check the variables with the leading and trailing spaces.
# of the given NBA dataset below.
# Later, strip those leading and trailing spaces in the identified variables.
# url = http://bit.ly/MSDS-NBADataset
df3=pd.read_csv("http://bit.ly/MSDS-NBADataset")
df3.head()

            Name            Team  Number  ... Weight            College     Salary
0  Avery Bradley  Boston Celtics     0.0  ...  180.0              Texas  7730337.0
1    Jae Crowder  Boston Celtics    99.0  ...  235.0          Marquette  6796117.0
2   John Holland  Boston Celtics    30.0  ...  205.0  Boston University        NaN
3    R.J. Hunter  Boston Celtics    28.0  ...  185.0      Georgia State  1148640.0
4  Jonas Jerebko  Boston Celtics     8.0  ...  231.0                NaN  5000000.0

[5 rows x 9 columns]

In [ ]:
#using strip
df3['Salary']
df3['Height'] = df3['Height'].str.strip()
df3

              Name            Team  ...            College     Salary
0    Avery Bradley  Boston Celtics  ...              Texas  7730337.0
1      Jae Crowder  Boston Celtics  ...          Marquette  6796117.0
2     John Holland  Boston Celtics  ...  Boston University        NaN
3      R.J. Hunter  Boston Celtics  ...      Georgia State  1148640.0
4    Jonas Jerebko  Boston Celtics  ...                NaN  5000000.0
..             ...             ...  ...                ...        ...
453   Shelvin Mack       Utah Jazz  ...             Butler  2433333.0
454      Raul Neto       Utah Jazz  ...                NaN   900000.0
455   Tibor Pleiss       Utah Jazz  ...                NaN  2900000.0
456    Jeff Withey       Utah Jazz  ...             Kansas   947276.0
457            NaN             NaN  ...                NaN        NaN

[458 rows x 9 columns]

In [ ]:
# Challenge 3
# Remove the text [edit] at the end of the university towns using the replace() function of the .str method
# Use the following dataset; url = http://bit.ly/MSUniversityTown
#
df_url="http://bit.ly/MSUniversityTown"
df5=pd.read_csv(df_url)

## 1.2 Accuracy

### <font color="green">1.2 Challenge</font>

In [ ]:
# Challenge 1: In-record & cross-datasets errors
# These errors result from having two or more values in the same row or across
# datasets that contradict with each other.
# For example, if we have a dataset about the cost of living in cities.
# The total column must be equivalent to the sum of rent, transport, and food.
# Similarly, a child can’t be married. An employee’s salary can’t be less than the calculated taxes etc.
# Using the given dataset below, determine and fix errors where the total population is not a sum of
# total male population and total female population
# dataset url = http://bit.ly/MSPopulationDistribution
# Hint: Review Pandas Basics
#
df2=pd.read_csv("http://bit.ly/MSPopulationDistribution")
df2

      Urban_Center  ... OBJECTID
0          NAIROBI  ...        0
1          MOMBASA  ...        1
2           KISUMU  ...        2
3           NAKURU  ...        3
4          ELDORET  ...        4
..             ...  ...      ...
210          SOTIK  ...      210
211  PORT VICTORIA  ...      211
212         OTHAYA  ...      212
213        KAJIADO  ...      213
214           WOTE  ...      214

[215 rows x 16 columns]

## 1.3 Completeness

In [ ]:
# Example 1: Checking/ Counting Missing Values
#

# Creating a dataframe to work with
df1 = {
    'Subject':['Humanities', 'Physical Education', 'Home Science', 'Mathematics', 'Physics',
               'Chemistry','Arts'],
   'Score':[62, 47, np.nan, 74, np.nan, 77, 85]}

df1 = pd.DataFrame(df1,columns=['Subject','Score'])

print(df1)

# Checking if there is any missing value in dataframe as a whole
# Uncomment the following line after running the previous lines
df1.isnull()

# Checking if there is any missing value across each column
# Uncomment the following line after running the previous lines
df1.isnull().any()

# Checking how many missing values there are across each column
# Uncomment the following line after running the previous lines
df1.isnull().sum()

# Or we can do a quick check to see if we have any missing values at all
# Uncomment the following line after running the previous lines
print(df1.isnull().values.any())

# We might also want to get a total count of missing values
# Uncomment the following line after running the previous lines
print(df1.isnull().sum())

In [ ]:
# Example 2: Dropping Missing Values
# If there are only a few null values and you know that deleting values
# will not cause adverse effects on your result,
# remove them from your DataFrame and store that in a new DataFrame

# Droppping all
# Uncomment the following 2 lines after running the previous lines
clean_df = df1.dropna()
print(clean_df)

# Verifying that you no longer have any null values by running
# Uncomment the following line after running the previous lines
print(clean_df.isnull().sum())

In [ ]:
# Exmaple 2: Dropping instances/records/rows with NA missing values
#

# Dropping all rows with any NA values
all_rows_any_na = df1.dropna()
print(all_rows_any_na)

# Dropping all rows that have all NA values
# Uncomment the 2 lines below after running the previous lines
all_rows_all_na = df1.dropna(how="all")
print(all_rows_all_na)

# We can also put a limitation on how many non-null values need to be in a row
# we can retain the data that has at least 2 non-null values as shown below
# Uncomment the 2 lines below after running the previous lines
df1_thresh = df1.dropna(thresh=2)
print(df1_thresh)

In [ ]:
# Example 2: Missing Values
# Dropping attributes (variables/columns)
# We can apply the same kind of criteria to our columns.
# We just need to use the parameter axis=1 in our code.
# That means to operate on columns, not rows.
# (We could have used axis=0 in our row examples,
# but it is 0 by default if you don’t enter anything.)
#

# Dropping all attributes with any NA values
#
all_cols_any_na = df1.dropna(axis=1)
print(all_cols_any_na)

# Dropping all attributes that have all NA values
# Uncomment the 2 lines below

# all_cols_all_na = df1.dropna(axis=1, how="all")
# print(all_cols_all_na)

# We can also put a limitation on how many non-null values need to be in a attributes
# we can retain the data that has at least 2 non-null values as shown below
# Uncomment the 2 lines below
# df1_thresh = df1.dropna(thresh=2)
# print(df1_thresh)

In [ ]:
# Example 3: Missing Values
# Imputing the attribute mean for all missing values
# Mean imputation replaces missing values with the mean value of that feature/variable.
# Mean imputation is one of the most ‘naive’ imputation methods
# because unlike more complex methods like k-nearest neighbors imputation,
# it does not use the information we have about an observation to estimate a value for it.

# Creating a dataframe to work with
subjects_df_mean = {
    'Subject':['Humanities', 'Physical Education', 'Home Science', 'Mathematics', 'Physics',
               'Chemistry','Arts'],
   'Score':[62, 47, np.nan, 74, np.nan, 77, 85]}
subjects_df_mean = pd.DataFrame(subjects_df_mean,columns=['Subject','Score'])

# printing our dataframe
print(subjects_df_mean)

# imputing the mean
subjects_df_mean['Score'] = subjects_df_mean['Score'].fillna((subjects_df_mean['Score'].mean()))

# printing out our updated dataframe
print(subjects_df_mean)

In [ ]:
# Example 4: Missing Values
# Imputing the attribute median for all missing values
#

# Creating a dataframe to work with
subjects_df_median = {
    'Subject':['Humanities', 'Physical Education', 'Home Science', 'Mathematics', 'Physics',
               'Chemistry','Arts'],
   'Score':[62, 47, np.nan, 74, np.nan, 77, 85]}
subjects_df_median = pd.DataFrame(subjects_df_median,columns=['Subject','Score'])

# printing our dataframe
print(subjects_df_median)

# imputing the median
subjects_df_median['Score'] = subjects_df_median['Score'].fillna((subjects_df_median['Score'].median()))

# printing out our updated dataframe
print(subjects_df_median)

In [ ]:
# Example 5: Missing Values
# Imputing the attribute mode for all missing values
#
# Creating a dataframe to work with
subjects_df_mode = {
    'Subject':['Humanities', 'Physical Education', 'Home Science', 'Mathematics', 'Physics',
               'Chemistry','Arts'],
   'Score':[62, 47, np.nan, 74, np.nan, 77, 85]}
subjects_df_mode = pd.DataFrame(subjects_df_mode,columns=['Subject','Score'])

# printing our dataframe
print(subjects_df_mode)

# imputing the mode
subjects_df_mode['Score'] = subjects_df_mode['Score'].fillna((subjects_df_mode['Score'].mode()))

# printing out our updated dataframe
print(subjects_df_mode)

In [ ]:
# Example 6: Missing Values
# Or maybe we just want to fill in missing values with a single value as shown below
#

df1 = {
    'Subject':['Humanities', 'Physical Education', 'Home Science', 'Mathematics', 'Physics',
               'Chemistry','Arts'],
   'Score':[62, 47, np.nan, 74, np.nan, 77, 85]}

df1 = pd.DataFrame(df1,columns=['Subject','Score'])

# Replace missing values with a number
df1['Score'].fillna(60, inplace=True)

print(df1)

In [ ]:
# Example 7: Missing Values
# Using the following property dataset, we will make a list of missing value types
# then load our dataset below
#

# reading our dataset
property_dataset = pd.read_csv("http://bit.ly/MS-PropertyDataset")
property_dataset

# Now making a list of missing value types found in our dataset
# Uncommenting the 3 lines below after running the previous lines
missing_values = ["n/a", "na", "--"]
property_dataset = pd.read_csv("http://bit.ly/MS-PropertyDataset", na_values = missing_values)
property_dataset

### <font color="green">1.3 Challenges</font>

In [ ]:
# Challenge 1
# Clean the following dataset that contains missing values
# url = http://bit.ly/DSRussianInvestigation
#
OUR CODE GOES HERE

In [ ]:
# Challenge 2
# Examine and clean the avengers dataset
# http://bit.ly/MSAvengers
#
OUR CODE GOES HERE

In [ ]:
# Challenge 3
# Clean the dataset where 16 multiple choice ability items were taken from the Synthetic Aperture Personality Assessment (SAPA)
# web based personality assessment project. The data from 1525 subjects are included as a demonstration
# set for scoring multiple choice inventories and doing basic item statistics.
# dataset url = http://bit.ly/MSIQQuestions
#
OUR CODE GOES HERE

In [ ]:
# Challenge 4
# The dataset below contains data from an experiment conducted by the Department of Biology
# at Kenyon College at a site near the campus in Gambier, Ohio. A student and faculty volunteers
# planted 1000 white pine (Pinus strobes) seedlings at the Brown Family Environmental Center.
# These seedlings were planted in two grids, distinguished by 10- and 15-foot spacings between the seedlings.
# Several variables were measured and recorded for each seedling over time (in 1990, 1996, and 1997).
# Handle the missing values of this dataset; dataset url = http://bit.ly/MSPines
#
# Features Description
# Row	Row number in pine plantation
# Col	Column number in pine plantation
# Hgt90	Tree height at time of planting (cm)
# Hgt96	Tree height in September 1996 (cm)
# Diam96	Tree trunk diameter in September 1996 (cm)
# Grow96	Leader growth during 1996 (cm)
# Hgt97	Tree height in September 1997 (cm)
# Diam97	Tree trunk diameter in September 1997 (cm)
# Spread97	Widest lateral spread in September 1997 (cm)
# Needles97	Needle length in September 1997 (mm)
# Deer95	Type of deer damage in September 1995: 0 = none, 1 = browsed
# Deer97	Type of deer damage in September 1997: 0 = none, 1 = browsed
# Cover95	Thorny cover in September 1995: 0 = none; 1 = some; 2 = moderate; 3 = lots
# Fert	Indicator for fertilizer: 0 = no, 1 = yes
# Spacing	Distance (in feet) between trees (10 or 15)
#
OUR CODE GOES HERE

In [ ]:
# Challenge 5
# Some geologists were interested in the water chemistry of rivers in Coastal New York.
# They took water samples at three different locations in four rivers.
# The sampling sites were chosen to investigate how the composition of the water changes
# as it flows from the source to the mouth of each river.
# The sampling sites were labeled as upstream, midstream, and downstream.
# This dataset contains the concentrations (parts per million) of a variety of elements in those water samples.
# The dataset RiverIron contains the information for iron (FE) alone, along with the log of the concentration.
# Handle the missing values found in this dataset; dataset url = http://bit.ly/MSRiverSamples

# Features Description
# River	One of four rivers: Grasse, Oswegatchie, Raquette, or St. Regis
# Site	Location: 1=UpStream, 2=MidStream, 3=Downstream
# Al	Aluminum
# Ba	Barium
# Br	Bromine
# Ca	Calcium
# Ce	Cerium
# Cu	Copper
# Dy	Dysprosium
# Er	Erbim
# Fe	Iron
# Gd	Gadolinium
# Ho	Holmum
# K	Potassium
# La	Lathanum
# Li	Lithium
# Mg	Magnesium
# Mn	Manganese
# Nd	Neodymium
# Pr	Proseyodymium
# Rb	Rubidium
# Si	Silicon
# Sr	Strontium
# Y	Yttrium
# Yb	Ytterbium
# Zn	Zinc
# Zr	Zirconium
#
OUR CODE GOES HERE

## 1.4 Consistency

In [ ]:
# Example 1: Duplicates
# Duplicates are data points that are repeated in your dataset.
# These should be simply removed.
#

raw_data = {'first_name': ['Jamila', 'Jamila', 'Jane','Joma', 'Ulia', 'Dorcas'],
        'last_name': ['Mohammed', 'Mohammed', 'Milner','Tech', 'Shevchenko', 'Wanjiru'],
        'age': [52, 52, 43, 77, 25, 19],
        'pre_assessment': [5, 5, 5, 43, 5, 2],
        'post_assessment': [35, 35, 25, 57, 72, 71]}
df_duplicate = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'pre_assessment', 'post_assessment'])
print(df_duplicate)


# Identifying which observations are duplicates
df_non_duplicates = df.drop_duplicates()

# Let's see these non-duplicate files
print(df_non_duplicates)

### <font color="green">1.4 Challenges</font>

In [ ]:
# Challenge  1
# Identify and handle the duplicted records found in the following dataset
# dataset url = http://bit.ly/MoviesDataset1
#
OUR CODE GOES HERE

In [ ]:
# Clean the following dataset
# dataset url = http://bit.ly/EmployeesDataset
#
OUR CODE GOES HERE

## 1.5 Uniformity

In [ ]:
# Example 1: Standardization - Renaming column names
# We can rename multiple  data frame column names in the following manner
#

# Create an example dataframe
#
officials_data = {'Moderator': ['Wanjiku', 'Muthoni', 'Kagure', 'Muema', 'Kariuki'],
        'Date': ['2015-02-11', '2013-02-22', '2015-02-11', '2014-02-11', '2011-02-11'],
        'Score': [14, 34, 41, 12, 13]}
officials_data = pd.DataFrame(officials_data)
print(officials_data)

# Renaming the column names
#
officials_data.columns = ['Senior Leader', 'Time', 'Score']
print(officials_data)

In [ ]:
# Example 2: Standardization - Fixing messy column names
# Sometimes you might have column names which are uppercase, with spaces,
# and whitespace all around. How do we fix this?
# We use the .str method that we use on text data.
# Ideally, we chain a bunch of .str functions as shown below;
#

# we use strip(), lower() and replace() functions
#
officials_data.columns = officials_data.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
print(officials_data)

In [ ]:
# Example 3: Date Type Conversion
# Make sure numbers are stored as numerical data types.
# A date should be stored as a date object, or a Unix timestamp (number of seconds), and so on.
# Making the respecive conversion is advised.
#

# Let's convert our strings to Datetime data type
# importing datatime module
from datetime import datetime

# Creating our data frame
data = {'date': ['2015-05-01 18:47:05.069722', '2015-05-01 18:47:05.119994',
                 '2015-05-02 18:47:05.178768', '2015-05-02 18:47:05.230071',
                 '2015-05-02 18:47:05.230071', '2015-05-02 18:47:05.280592',
                 '2015-05-03 18:47:05.332662', '2015-05-03 18:47:05.385109',
                 '2015-05-04 18:47:05.436523', '2015-05-04 18:47:05.486877'],
        'value': [1, 2, 4, 5, 6, 3, 2, 1, 15, 11]}
df = pd.DataFrame(data, columns = ['date', 'value'])

# printing our dataframe
print(df.info())

# Converting date column from string to datetime
df['date'] = pd.to_datetime(df['date'])

# printing our updated dataframe
print(df.info())

In [ ]:
#checking datatype
sales_df.dtypes

Customer Number    float64
Customer Name       object
2016                object
2017                object
Percent Growth      object
Jan Units           object
Month                int64
Day                  int64
Year                 int64
Active              object
dtype: object

In [ ]:
df['Customer Number'] = df['Customer Number'].astype(int)
df['Percent Growth'] = df['Percent Growth'].str.rstrip('%').astype('float') / 100
df['Jan Units'] = df['Jan Units'].replace('Closed' , 0).astype(int)
df[df.columns[2:4]] = df[df.columns[2:4]].replace('[\$,]', '', regex=True).astype(float)
from datetime import datetime
df['Date'] = pd.to_datetime(df[["Year",'Month','Day']])
df['Total'] = df['2016'] + df['2017']
df.drop(['Year','Day','Month'],axis=1,inplace=True)
df=df.replace({"Active" :{"Y" :True ,'N' :False}})
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer Number  5 non-null      int64
 1   Customer Name    5 non-null      object
 2   2016             5 non-null      float64
 3   2017             5 non-null      float64
 4   Percent Growth   5 non-null      float64
 5   Jan Units        5 non-null      int64
 6   Active           5 non-null      bool
 7   Date             5 non-null      datetime64[ns]
 8   Total            5 non-null      float64
dtypes: bool(1), datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 453.0+ bytes

   Customer Number     Customer Name      2016  ...  Active       Date      Total
0            10002  Quest Industries  125000.0  ...    True 2015-01-10   287500.0
1           552278    Smith Plumbing  920000.0  ...    True 2014-06-15  1932000.0
2            23477   ACME Industrial   50000.0  ...    True 2016-03-29   112500.0
3            24900        Brekke LTD  350000.0  ...    True 2015-10-27   840000.0
4           651029         Harbor Co   15000.0  ...   False 2014-02-02    27750.0

[5 rows x 9 columns]