<a href="https://colab.research.google.com/github/joyangelai/Colabs/blob/main/Linear_regression_multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [ ]:
# load dataset
data = pd.read_csv("/homeprices (1).csv")
data

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# get summary stats
data.describe()

              area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [ ]:
# check shape
data.shape

(6, 4)

In [ ]:
# check info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int64
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64
 3   price     6 non-null      int64
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes

In [ ]:
# filling in missing values
data.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [ ]:
# using median
bedm = data['bedrooms'].median()
bedm

4.0

In [ ]:
# filling in missing values
data.fillna({'bedrooms' : bedm}, inplace=True)

In [ ]:
# checking for null values again
data.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [ ]:
# divide data into X and y
X = data.drop("price", axis=1)
y = data['price']

In [ ]:
# scale the model
from sklearn.preprocessing import StandardScaler

scl = StandardScaler()
x_scale = scl.fit_transform(X)
x_scale

array([[-1.52162173, -1.09321633,  0.46257302],
       [-0.77633762, -0.15617376, -0.19824558],
       [-0.40369556, -0.15617376,  0.19824558],
       [ 0.34158855, -1.09321633,  1.78421022],
       [ 1.08687266,  0.78086881, -1.12339162],
       [ 1.27319369,  1.71791138, -1.12339162]])

In [ ]:
# init the model
mlr = linear_model.LinearRegression()
mlr

# train the model
mlr.fit(x_scale,y)

LinearRegression()

In [ ]:
# check coefficient
mlr.coef_

array([ 60144.81726336,  24960.31748558, -24452.38304739])

In [ ]:
# check intercept
mlr.intercept_  # --> this is the same as b0

np.float64(648333.3333333334)

In [ ]:
# predict manually  y = b0 + b1x1 + b2x2 + ..... +  bnxn
y =  648333.3333333334 + (60144.81726336 * data['area']) + (24960.31748558* data['bedrooms']) + (-24452.38304739* data['age'])